-- Automatizacion para Polla Mundial 2026
-- Ejecuta este archivo en Supabase SQL Editor despues de schema.sql y policies.sql.
-- Agrega campos para enlazar partidos locales con un proveedor externo y auditar sincronizaciones.

begin;

alter table public.matches
  add column if not exists external_provider text,
  add column if not exists external_fixture_id text,
  add column if not exists last_synced_at timestamptz,
  add column if not exists sync_note text;

create unique index if not exists idx_matches_external_fixture
on public.matches (external_provider, external_fixture_id)
where external_provider is not null and external_fixture_id is not null;

create table if not exists public.automation_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null default 'ok' check (status in ('ok', 'warning', 'error')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  matches_seen integer not null default 0,
  matches_updated integer not null default 0,
  message text
);

alter table public.automation_runs enable row level security;

drop policy if exists automation_runs_admin_select on public.automation_runs;
create policy automation_runs_admin_select
on public.automation_runs
for select
to authenticated
using (public.is_admin(auth.uid()));

revoke all on table public.automation_runs from anon, authenticated;
grant select on table public.automation_runs to authenticated;
grant usage, select on sequence public.automation_runs_id_seq to authenticated;

commit;
