-- Polla Mundial 2026 - esquema base
-- Ejecuta este archivo primero en Supabase SQL Editor.

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  alias text unique not null check (length(trim(alias)) > 0),
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_number integer unique,
  phase text,
  group_name text,
  home_team text,
  away_team text,
  match_date timestamptz,
  stadium text,
  city text,
  home_score integer check (home_score is null or home_score >= 0),
  away_score integer check (away_score is null or away_score >= 0),
  status text not null default 'scheduled' check (status in ('scheduled', 'live', 'finished')),
  created_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  predicted_home_score integer check (predicted_home_score is null or predicted_home_score >= 0),
  predicted_away_score integer check (predicted_away_score is null or predicted_away_score >= 0),
  points integer not null default 0,
  exact_score boolean not null default false,
  correct_result boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, match_id)
);

create table if not exists public.bonus_predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  champion text,
  runner_up text,
  top_scorer text,
  surprise_team text,
  points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id)
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_matches_date on public.matches(match_date);
create index if not exists idx_matches_phase on public.matches(phase);
create index if not exists idx_predictions_user_id on public.predictions(user_id);
create index if not exists idx_predictions_match_id on public.predictions(match_id);
create index if not exists idx_bonus_predictions_user_id on public.bonus_predictions(user_id);

insert into public.settings (key, value) values
  ('scoring_rules', '{"exact_score": 3, "correct_result": 1, "champion": 5, "runner_up": 3}'::jsonb),
  ('bonus_lock_at', '{"lock_at": "2026-06-11T00:00:00.000Z"}'::jsonb),
  ('official_result', '{"champion": null, "runner_up": null}'::jsonb)
on conflict (key) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  raw_alias text;
  raw_full_name text;
begin
  raw_alias := nullif(trim(new.raw_user_meta_data->>'alias'), '');
  raw_full_name := nullif(trim(new.raw_user_meta_data->>'full_name'), '');

  if raw_alias is null then
    raise exception 'El alias es obligatorio';
  end if;

  insert into public.profiles (id, email, full_name, alias, role)
  values (new.id, new.email, raw_full_name, raw_alias, 'user');

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.is_admin(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = check_user_id
      and p.role = 'admin'
  );
$$;

create or replace function public.is_match_open_for_predictions(check_match_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.matches m
    where m.id = check_match_id
      and m.status = 'scheduled'
      and (m.match_date is null or m.match_date > now())
  );
$$;

create or replace function public.is_bonus_open()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select (s.value->>'lock_at')::timestamptz > now()
    from public.settings s
    where s.key = 'bonus_lock_at'
  ), true);
$$;

create or replace function public.match_result(home_score integer, away_score integer)
returns text
language sql
immutable
as $$
  select case
    when home_score is null or away_score is null then null
    when home_score > away_score then 'home_win'
    when away_score > home_score then 'away_win'
    else 'draw'
  end;
$$;

create or replace function public.compute_match_points(
  predicted_home integer,
  predicted_away integer,
  actual_home integer,
  actual_away integer,
  match_status text
)
returns table(points integer, exact_score boolean, correct_result boolean)
language sql
stable
set search_path = public
as $$
  with rules as (
    select
      coalesce((value->>'exact_score')::integer, 3) as exact_score_points,
      coalesce((value->>'correct_result')::integer, 1) as correct_result_points
    from public.settings
    where key = 'scoring_rules'
  ), defaults as (
    select
      coalesce((select exact_score_points from rules), 3) as exact_score_points,
      coalesce((select correct_result_points from rules), 1) as correct_result_points
  )
  select
    case
      when match_status <> 'finished' then 0
      when predicted_home is null or predicted_away is null or actual_home is null or actual_away is null then 0
      when predicted_home = actual_home and predicted_away = actual_away then defaults.exact_score_points
      when public.match_result(predicted_home, predicted_away) = public.match_result(actual_home, actual_away) then defaults.correct_result_points
      else 0
    end as points,
    case
      when match_status = 'finished'
       and predicted_home is not null and predicted_away is not null and actual_home is not null and actual_away is not null
       and predicted_home = actual_home and predicted_away = actual_away
      then true else false
    end as exact_score,
    case
      when match_status = 'finished'
       and predicted_home is not null and predicted_away is not null and actual_home is not null and actual_away is not null
       and public.match_result(predicted_home, predicted_away) = public.match_result(actual_home, actual_away)
      then true else false
    end as correct_result
  from defaults;
$$;

create or replace function public.set_prediction_scores()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  match_record public.matches%rowtype;
  computed_points integer;
  computed_exact boolean;
  computed_correct boolean;
begin
  if current_setting('app.skip_prediction_score_trigger', true) = 'on' then
    new.updated_at = now();
    return new;
  end if;

  select * into match_record
  from public.matches
  where id = new.match_id;

  select c.points, c.exact_score, c.correct_result
    into computed_points, computed_exact, computed_correct
  from public.compute_match_points(
    new.predicted_home_score,
    new.predicted_away_score,
    match_record.home_score,
    match_record.away_score,
    match_record.status
  ) c;

  new.points := coalesce(computed_points, 0);
  new.exact_score := coalesce(computed_exact, false);
  new.correct_result := coalesce(computed_correct, false);
  new.updated_at := now();

  return new;
end;
$$;

drop trigger if exists set_prediction_scores_trigger on public.predictions;
create trigger set_prediction_scores_trigger
  before insert or update on public.predictions
  for each row execute function public.set_prediction_scores();

drop trigger if exists set_bonus_updated_at_trigger on public.bonus_predictions;
create trigger set_bonus_updated_at_trigger
  before update on public.bonus_predictions
  for each row execute function public.set_updated_at();

drop trigger if exists set_settings_updated_at_trigger on public.settings;
create trigger set_settings_updated_at_trigger
  before update on public.settings
  for each row execute function public.set_updated_at();

create or replace function public.compute_bonus_points(champion_prediction text, runner_up_prediction text)
returns integer
language sql
stable
set search_path = public
as $$
  with rules as (
    select
      coalesce((value->>'champion')::integer, 5) as champion_points,
      coalesce((value->>'runner_up')::integer, 3) as runner_up_points
    from public.settings
    where key = 'scoring_rules'
  ), official as (
    select
      value->>'champion' as champion,
      value->>'runner_up' as runner_up
    from public.settings
    where key = 'official_result'
  ), defaults as (
    select
      coalesce((select champion_points from rules), 5) as champion_points,
      coalesce((select runner_up_points from rules), 3) as runner_up_points,
      (select champion from official) as champion,
      (select runner_up from official) as runner_up
  )
  select
    case
      when nullif(trim(coalesce(defaults.champion, '')), '') is not null
       and lower(trim(coalesce(champion_prediction, ''))) = lower(trim(defaults.champion))
      then defaults.champion_points else 0 end
    +
    case
      when nullif(trim(coalesce(defaults.runner_up, '')), '') is not null
       and lower(trim(coalesce(runner_up_prediction, ''))) = lower(trim(defaults.runner_up))
      then defaults.runner_up_points else 0 end
  from defaults;
$$;

create or replace function public.set_bonus_points()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.points := public.compute_bonus_points(new.champion, new.runner_up);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_bonus_points_trigger on public.bonus_predictions;
create trigger set_bonus_points_trigger
  before insert or update on public.bonus_predictions
  for each row execute function public.set_bonus_points();

create or replace function public.refresh_prediction_scores_for_match()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform set_config('app.skip_prediction_score_trigger', 'on', true);

  with recalculated as (
    select p.id, c.points, c.exact_score, c.correct_result
    from public.predictions p
    cross join lateral public.compute_match_points(
      p.predicted_home_score,
      p.predicted_away_score,
      new.home_score,
      new.away_score,
      new.status
    ) c
    where p.match_id = new.id
  )
  update public.predictions p
  set points = r.points,
      exact_score = r.exact_score,
      correct_result = r.correct_result,
      updated_at = now()
  from recalculated r
  where p.id = r.id;

  return new;
end;
$$;

drop trigger if exists refresh_prediction_scores_for_match_trigger on public.matches;
create trigger refresh_prediction_scores_for_match_trigger
  after update of home_score, away_score, status on public.matches
  for each row execute function public.refresh_prediction_scores_for_match();

create or replace function public.recalculate_match_points(p_match_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Solo un administrador puede recalcular puntos';
  end if;

  perform set_config('app.skip_prediction_score_trigger', 'on', true);

  with recalculated as (
    select p.id, c.points, c.exact_score, c.correct_result
    from public.predictions p
    join public.matches m on m.id = p.match_id
    cross join lateral public.compute_match_points(
      p.predicted_home_score,
      p.predicted_away_score,
      m.home_score,
      m.away_score,
      m.status
    ) c
    where p.match_id = p_match_id
  )
  update public.predictions p
  set points = r.points,
      exact_score = r.exact_score,
      correct_result = r.correct_result,
      updated_at = now()
  from recalculated r
  where p.id = r.id;
end;
$$;

create or replace function public.recalculate_bonus_points()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Solo un administrador puede recalcular bonus';
  end if;

  update public.bonus_predictions bp
  set points = public.compute_bonus_points(bp.champion, bp.runner_up),
      updated_at = now();
end;
$$;

create or replace function public.recalculate_all_points()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Solo un administrador puede recalcular la tabla';
  end if;

  perform set_config('app.skip_prediction_score_trigger', 'on', true);

  with recalculated as (
    select p.id, c.points, c.exact_score, c.correct_result
    from public.predictions p
    join public.matches m on m.id = p.match_id
    cross join lateral public.compute_match_points(
      p.predicted_home_score,
      p.predicted_away_score,
      m.home_score,
      m.away_score,
      m.status
    ) c
  )
  update public.predictions p
  set points = r.points,
      exact_score = r.exact_score,
      correct_result = r.correct_result,
      updated_at = now()
  from recalculated r
  where p.id = r.id;

  update public.bonus_predictions bp
  set points = public.compute_bonus_points(bp.champion, bp.runner_up),
      updated_at = now();
end;
$$;

create or replace function public.admin_override_prediction_points(
  p_prediction_id bigint,
  p_points integer,
  p_exact_score boolean default false,
  p_correct_result boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Solo un administrador puede modificar puntos';
  end if;

  perform set_config('app.skip_prediction_score_trigger', 'on', true);

  update public.predictions
  set points = p_points,
      exact_score = p_exact_score,
      correct_result = p_correct_result,
      updated_at = now()
  where id = p_prediction_id;
end;
$$;

create or replace function public.set_user_role(target_user_id uuid, new_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Solo un administrador puede cambiar roles';
  end if;

  if new_role not in ('user', 'admin') then
    raise exception 'Rol inválido';
  end if;

  update public.profiles
  set role = new_role
  where id = target_user_id;
end;
$$;

create or replace view public.leaderboard_view as
select
  p.id as user_id,
  p.alias,
  coalesce(sum(pr.points), 0)::integer + coalesce(bp.points, 0)::integer as total_points,
  count(pr.id) filter (where pr.exact_score)::integer as exact_scores,
  count(pr.id) filter (where pr.correct_result)::integer as correct_results,
  coalesce(bp.points, 0)::integer as bonus_points,
  bp.champion,
  bp.runner_up,
  greatest(
    coalesce(max(pr.updated_at), p.created_at),
    coalesce(bp.updated_at, p.created_at)
  ) as last_updated
from public.profiles p
left join public.predictions pr on pr.user_id = p.id
left join public.bonus_predictions bp on bp.user_id = p.id
group by p.id, p.alias, p.created_at, bp.points, bp.champion, bp.runner_up, bp.updated_at;

create or replace view public.predictions_export_view
with (security_invoker = true)
as
select
  pr.id,
  p.alias,
  m.match_number,
  m.phase,
  m.group_name,
  m.home_team,
  m.away_team,
  m.match_date,
  pr.predicted_home_score,
  pr.predicted_away_score,
  m.home_score,
  m.away_score,
  pr.points,
  pr.exact_score,
  pr.correct_result,
  pr.updated_at
from public.predictions pr
join public.profiles p on p.id = pr.user_id
join public.matches m on m.id = pr.match_id;

commit;
